        <nav>
            <a href='<?=URL_BASE?>/index.php/Auth/logout' id='logout'>LOGOUT</a>
            <ul>
                <li><a href='#'>UTILITARIO</a></li>
                <li><a href='#'>ESTOQUE</a></li>
                <li><a href='#'>RELATORIOS</a></li>
                <li><a href='#'>CLIENTES</a></li>
                <li><a href='<?=URL_BASE?>/index.php/User/list'>USUARIOS</a></li>
            </ul>
        </nav>
