        <nav>
            <a href='<?=URL_BASE?>/index.php/Auth/logout' id='logout'>LOGOUT</a>
            <ul>
                <li><a href='#'>ESTOQUE</a>
					<!--<ul id=submenu>
						<li class=listmenu><a href='#'>Cadastro de Produtos</a></li>
						<li class=listmenu><a href='#'>Cadastro de Grupos</a></li>
						<li class=listmenu><a href='#'>Cadastro de Família</a></li>
						<li class=listmenu><a href='#'>Cadastro de Local</a></li>
					</ul> -->	
				</li>
                <li><a href='#'>RELATORIOS</a></li>
                <li><a href='<?=URL_BASE?>/index.php/Client/listall'>CLIENTES</a></li>
                <li><a href='<?=URL_BASE?>/index.php/User/listall'>USUARIOS</a></li>
            </ul>
        </nav>
