<!DOCTYPE HTML>
<html lang="pt-br">
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" type="text/css" href="public/css/style.css">
		<title>Sigec - Sistema de Gerenciamento e Controle</title>
	</head>
	<body>
		<?php 
			include('templates/header.phtml');
			include('templates/nav.phtml');
			include('templates/content.phtml');
			include('templates/aside.phtml');
		?>
		<div id='clear'></div>
		<?php include('templates/footer.phtml');?>
	</body>
</html>

