<!DOCTYPE HTML>
<html lang="pt-br">
    <?php include('templates/head.phtml');?>
	<body>
        <?php include('templates/header.phtml');?>
        <?php include('templates/nav.phtml');?>        
        <main id='welcome'>
            <h1> Seja bem vindo!! </h1>
            <h2> ao </h2>
            <h1> SIGEC </h1>
		</main>
        <?php include('templates/aside.phtml');?>
		<div id='clear'></div>
		<?php include('templates/footer.phtml');?>
	</body>
</html>

