<!DOCTYPE HTML>
<html lang="pt-br">
    <?php include('templates/head.phtml');?>
	<body>
        <?php include('templates/header.phtml');?>
        <?php include('templates/nav.phtml');?>
        <main id='users-list'>
            <?php if($action == 'add'):?>
                <div>
                    <h3>Inclusao de Usuario</h3>
                    <form action='<?=URL_BASE?>/index.php/User/save' method="post">
                        <label> 
                            <span>Nome: </span>
                            <input id='name' type='text' value='<?=@$post->name?>' name='name' required maxlength='40' />
                        </label>
                        <label> 
                            <span>Login:</span>
                            <input id='login' type='text' value='<?=@$post->login?>' name='login' required maxlength=40 />
                        </label>
                        <label> 
                            <span>Senha:</span>
                            <input id='password' type='password' name='password' required maxlength=40 />
                        </label>
                        <label> 
                            <span>Repita senha:</span>
                            <input id='rpassword' type='password' name='rpassword' required maxlength=40 />
                        </label>
                        <!--label> 
                            <span>Email:</span>
                            <input id='email' type='email' value='<?=@$post->email?>' name='email' required maxlength=40 />
                        </label-->
                        <label> 
                            <span>Perfil:</span>
                            <select name='profile' required>
                                <option value=""> -- Selecione -- </option>
                                <option value="administrador" <?php echo (@$post->profile == 'administrador') ? 'selected' : '' ?> >Administrador</option>
                                <option value="usuario" <?php echo (@$post->profile == 'usuario') ? 'selected' : '' ?> >Usuario</option>
                            </select> 
                        </label>

                        <input type="submit" value="Gravar">
                        <input type="button" value="Fechar" onclick="location.href='<?=URL_BASE?>/index.php/Main'">
                    </form>
                    <?php foreach($errors as $erro): ?>
                        <span><?=$erro?></span>
                    <?php endforeach;?>
                </div> 

            <?php elseif($action == 'update'):?>
                <div>UPDATE </div> 

            <?php else: ?>
                <div id='users-list'>
                    <ul>
                        <li>
                            <ul>
                                <li>Codigo</li>
                                <li>Nome</li>
                                <li>Login</li>
                                <li>Ativo/Inativo</li>
                            </ul>
                        </li>
                        <?php foreach($users as $user): ?>
                        <li>
                            <ul>
                                <li><?=$user->ID?></li>
                                <li><?=$user->NOME?></li>
                                <li><?=$user->LOGIN?></li>
                                <li><?=$user->ATIVO?></li>
                            </ul>
                        </li>
                        <?php endforeach;?>
                    </ul>
                    <input type="button" value="Novo" onclick="location.href='<?=URL_BASE?>/index.php/User/add'" />
                    <input type="button" value="Alterar" onclick="location.href='<?=URL_BASE?>/index.php/User/update/'" />
                    <input type="button" value="Fechar" onclick="location.href='<?=URL_BASE?>/index.php/Main'" />
                </div>
            <?php endif;?>
		</main>
        <?php include('templates/aside.phtml');?>
		<div id='clear'></div>
		<?php include('templates/footer.phtml');?>
	</body>
</html>

