<!DOCTYPE HTML>
<html lang="pt-br">
    <?php include('templates/head.phtml');?>
	<body>
        <?php include('templates/header.phtml');?>
        <?php include('templates/nav.phtml');?>
        <main>
            <?php if($action == 'add'):?>
                <div id="add">
				    <h1 id='adduser'>Inclusão de Usuário</h1>
                    
                    <form id="add_user"action='<?=URL_BASE?>/index.php/User/save/action/add' method="post">
                        <label> 
                            <span id="name">Nome: </span>
                            <input id='name' type='text' value='<?=@$user->name?>' name='name' required maxlength='40' />
                        </label>
                        </br>
						</br>
						<label> 
                            <span id="login">Login:</span>
                            <input id='login' type='text' value='<?=@$user->login?>' name='login' required maxlength=40  />
                        </label>
						</br>
						</br>
                        <label> 
                            <span id="password">Senha:</span>
                            <input id='password' type='password' value='<?=@$user->password?>'name='password' required maxlength=40 />
                        </label>
						</br>
						</br>
                        <label id="rpassword"> 
                            <span id="rpassword">Repita senha:</span>
                            <input id='rpassword' type='password'value='<?=@$user->password?>' name='rpassword' required maxlength=40 />
                        </label>
						</br>
						</br>
                        <label id="profile"> 
                            <span id="perfil">Perfil:</span>
                            <select id ="profile" name='profile' required>
                                <option value=""> -- Selecione -- </option>
                                <option value="administrador" <?php echo (@$user->profile == 'administrador') ? 'selected' : '' ?> >Administrador</option>
                                <option value="usuario" <?php echo (@$user->profile == 'usuario') ? 'selected' : '' ?> >Usuario</option>
                            </select> 
                        </label>
                        </br>
						</br>
                        <input type="hidden" name='id' value='0'/>
                        <input type="submit" value="Gravar" id="gravar">
                        <input type="button" value="Fechar" id="close" onclick="location.href='<?=URL_BASE?>/index.php/Main'">
                    </form>
                    <?php foreach($errors as $erro): ?>
                        <span><?=$erro?></span>
                    <?php endforeach;?>
                </div> 

            <?php elseif($action == 'update'):?>
                <div>
                    <h1 id=update-user>Edição de Usuário</h1>
                    
                    <form id="update_user" action='<?=URL_BASE?>/index.php/User/save/action/update' method="post">
                        <label> 
                            <span id="name">Nome: </span>
                            <input id='name' type='text' value='<?=@$user->name?>' name='name' required maxlength='40' />
                        </label>
                        </br>
						</br>
						<label> 
                            <span id="login">Login:</span>
                            <input id='login' type='text' value='<?=@$user->login?>' name='login' required maxlength=40  />
                        </label>
						</br>
						</br>
                        <label> 
                            <span id="password">Senha:</span>
                            <input id='password' type='password' name='password' required maxlength=40 />
                        </label>
						</br>
						</br>
                        <label id="rpassword"> 
                            <span id="rpassword">Repita senha:</span>
                            <input id='rpassword' type='password' name='rpassword' required maxlength=40 />
                        </label>
						</br>
						</br>
                        <label id="profile"> 
                            <span id="perfil">Perfil:</span>
                            <select id ="profile" name='profile' required>
                                <option value=""> -- Selecione -- </option>
                                <option value="administrador" <?=(@$user->profile == 'administrador') ? 'selected' : '' ?> >Administrador</option>
                                <option value="usuario" <?=(@$user->profile == 'usuario') ? 'selected' : '' ?> >Usuario</option>
                            </select> 
                        </label>
                        </br>
						</br>
                        <input type="hidden" name='id' value='<?=@$user->id ? $user->id : 0 ?>'/>
                        <input type="submit" value="Gravar" id="gravar">
                        <input type="button" value="Fechar" id="close" onclick="location.href='<?=URL_BASE?>/index.php/Main'">
                    </form></div> 
                    <?php foreach($errors as $erro): ?>
                        <span><?=$erro?></span>
                    <?php endforeach;?>

            <?php else: ?>
            			
                <div id='users-list'>
					<div id="filtro-lateral">
						<div id=search_lateral>
							<header id=lateral>
								<h1 id="filter_por">Filtrar Por: </h1>
							</header>
						</div>
						<form>	
						<input type="radio" name="filter" value="cod" checked id="rdio">Código
						</br>
						</br>
						<input type="radio" name="filter" value="name" id="rdio">Nome
						</br>
						</br>
						<input type="radio" name="filter" value="login" id="rdio">Login
						</br>
						</br>
						</form>

					</div>
					<div id="search">
							<div id=search_name>
								<header id=search>
									<h1 id="filter">Filtro</h1>
								</header>
							</div>
							<form id='name'>Nome: <input id="camp" type="text" name="search_name" required maxlength='40'></form>
					        <input type="submit" value="Filtrar" id="filter_bottom"> 
							<input type="submit" value="Mostrar Todos" id="mostrar">
					</div>
					<div id="list">
						<table style="undefined;table-layout: fixed; width: 100%;">
							<colgroup>
							<col style="width: 50px">
							<col style="width: 100px">
							<col style="width: 100px">
							<col style="width: 100px">
                            </colgroup>
                            <thead>
                                <tr>
                                    <th>Codigo</th>
                                    <th>Nome</th>
                                    <th>Login</th>
                                    <th>Ativo/Inativo</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach($users as $user): ?>
                                <tr>
                                    <td><?=$user->ID?></td>
                                    <td><?=$user->NOME?></td>
                                    <td><?=$user->LOGIN?></td>
                                    <td><?=$user->ATIVO?></td>
                                </tr>
                                <?php endforeach;?>
                            </tbody>
						</table>
							
                    </div>
                    <input type="hidden" name='id' value='0'/>
                    <input type="button" value="Novo" id="novo" onclick="location.href='<?=URL_BASE?>/index.php/User/add'" />
                    <input type="button" value="Alterar" id="edicao" onclick="userUpdate();" />
                    <input type="button" value="Fechar" id="fecha" onclick="location.href='<?=URL_BASE?>/index.php/Main'" />
                </div>
            <?php endif;?>
            <input type="hidden" id='url-base' value='<?=URL_BASE?>'/>
		</main>
        <?php include('templates/aside.phtml');?>
		<div id='clear'></div>
        <?php include('templates/footer.phtml');?>
        <script src='<?=PUBLIC_URL?>/js/jquery-1.11.2.min.js'></script>
        <script src='<?=PUBLIC_URL?>/js/sigec.js'></script>
	</body>
</html>

